### ISSUE TITLE
Параметры бэкапа mysql

### ISSUE THREAD

**Issue by Metotron** [vladios13/site-backupsh#1]
Не стоит ли к mysqldump добавить -R и --triggers? И возможно ещё -l, а то даже и всю базу блокировать, чтобы не получить разрозненные данные в бэкапе.

**Comment by vladios13** [comment]
@Metotron Добавил ключ -l для блокировки таблиц на время дампа. 
Commit: https://github.com/vladios13/site-backupsh/commit/046b0fc6271bb923cdb8b68e48b53f1df6721c39

А разве `--triggers` не включен по умолчанию?
